### ISSUE TITLE
在python2.7 安装时有点问题

### ISSUE THREAD

**Issue by hy9125** [dequinns/ScrapydArt#2]
**现象：**
```
Collecting scrapydart
  Downloading http://mirrors.aliyun.com/pypi/packages/7f/4e/270ce06369af17c1d0edce3407ebb906538405496c269826d82f8fee95e9/scrapydart-1.2.0.5.tar.gz (79kB)
    100% |████████████████████████████████| 81kB 399kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/nx/v32f9xgs3rx851935jywyxlw0000gn/T/pip-install-q_3gar/scrapydart/setup.py", line 20, in <module>
        'long_description': open('README.rst', encoding="utf-8").read(),
    TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by dequinns** [comment]
不好意思，回复晚了。这个主要是由于我没有考虑py2.7和py3的兼容性导致的，可以看到报错主要是因为README的读取和编码产生的错误。目前来说，暂时只支持py3。

**Comment by hy9125** [comment]
感谢回复。那我希望最好在项目中标明一下。
如果只是文件编码不支持2，而项目编码中支持2。这块儿是可以修改的。
